from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import uvicorn

from ecommerce_churn_ltv.pipelines.prediction_pipeline import PredictPipeline, CustomData
from ecommerce_churn_ltv.logger import logging

app = FastAPI(
    title="E-Commerce Customer Churn & LTV API",
    description="Production REST API for predicting customer churn risk and evaluating RFM profiles.",
    version="1.0.0"
)

# Define API request body schema using Pydantic for validation
class CustomerDataRequest(BaseModel):
    recency: float = Field(..., example=120.0, description="Days since last customer transaction")
    frequency: float = Field(..., example=2.0, description="Total number of completed orders")
    monetary: float = Field(..., example=150.0, description="Total revenue generated by customer")
    avg_order_value: float = Field(..., example=75.0, description="Average spend per order")


@app.get("/")
def read_root():
    """Health check endpoint to verify API is active."""
    return {"status": "online", "message": "E-Commerce Churn Prediction API is running."}


@app.post("/predict")
def predict_churn(data: CustomerDataRequest):
    """Predicts customer churn status and probability based on RFM metrics."""
    try:
        logging.info("API Request received for churn prediction.")
        
        # 1. Map API payload to CustomData structure
        customer = CustomData(
            recency=data.recency,
            frequency=data.frequency,
            monetary=data.monetary,
            avg_order_value=data.avg_order_value
        )
        
        # 2. Format as DataFrame
        input_df = customer.get_data_as_data_frame()
        
        # 3. Predict via pipeline
        pipeline = PredictPipeline()
        prediction, probability = pipeline.predict(input_df)
        
        churn_status = "Churn Risk" if int(prediction) == 1 else "Active Customer"
        
        return {
            "prediction": churn_status,
            "churn_class": int(prediction),
            "churn_probability_percentage": round(float(probability) * 100, 2),
            "input_metrics": data.dict()
        }

    except Exception as e:
        logging.error(f"API Error during prediction: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)